import Head from "next/head";

import {
  AiOutlineGithub,
  AiFillLinkedin,
  AiFillCode,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.jpg";
import reactt from "../public/React-icon.svg.png";
import cpp from "../public/pngwing.com.png";
import python from "../public/python-svgrepo-com.svg";
import Image from "next/image";
import flutter from "../public/flutter-svgrepo-com.svg";
import sql from "../public/sql-database-sql-azure-svgrepo-com.svg";



export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>My Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">WELCOME</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://drive.google.com/file/d/1Tpc8FCqUB-XeAOd7sQvCT91eR-qgTIVV/view?usp=drive_link"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Srinivas Rao Uttarkar
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Software Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://github.com/srinusrinivas07"> 
              <AiOutlineGithub />
              </a>
              <a href="https://www.linkedin.com/in/srinivas-uttarkar/">
              <AiFillLinkedin />
              </a>
              <a href="https://www.codechef.com/users/srinu1345">
              <AiFillCode />
              </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image alt="react" src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">About Me</h3>
            <div className="text-justify shadow-lg p-5 rounded-xl my-10  dark:bg-white flex-1" style={{background: "linear-gradient(to right,#facf6e, #C5FAD5)"}}>
            <p className="text-md py-2 leading-8 text-gray-800 ">
            Hello! I'm Srinivas, a passionate and driven software developer and a final year student of Bachelor of Engineering in Computer Science from Sathyabama Institute of Science & Technology, Chennai with a strong love for turning ideas into reality through elegant and efficient code.With a solid foundation in computer science. My journey as a software developer has allowed me to work on diverse projects, ranging from web applications and mobile apps to complex backend systems and software solutions. I enjoy solving technical problems, researching and developing new technologies, and interacting with clients and customers. I am a quick learner with a fun, outgoing personality, and I excel in working under pressure and handling stressful situations. My goal is to get a full-time job in the information technology field after graduating in 2024, where I can apply my skills and knowledge, and contribute to the success of the organization.
            
            </p>
              
            </div>
          </div>
          <br></br>
          <h3 className="text-3xl py-1 dark:text-white ">skills</h3>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1" style={{ background: "linear-gradient(to right, #facf6e, #C5FAD5)" }}>
              <Image src={cpp} width={95} height={90}/>
              
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1" style={{background: "linear-gradient(to left, #facf6e, #C5FAD5)"}}>
              <Image alt="react" src={reactt} width={100} height={90}/>
              
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1" style={{background: "linear-gradient(to right,#facf6e, #C5FAD5)"}}>
              <Image alt="react" src={python} width={100} height={100} sizes="10" />
              
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1"style={{background: "linear-gradient(to left, #facf6e, #C5FAD5)"}}>
              <Image alt="react" src={flutter} width={100} height={100} sizes="10"/>
              
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1"style={{background: "linear-gradient(to right, #facf6e, #C5FAD5)"}}>
              <Image alt="react" src={sql} width={100} height={90} />
              
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">projects</h3>
          </div>
          <section>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1" style={{background: "linear-gradient(to right, #facf6e, #C5FAD5)"}}>
            
            <h1 className="font-burtons text-xl text-3xl py-1 mb-8 ">INSTAGRAM CLONE</h1>
              
                <a
                  className="bg-gradient-to-r hover:bg-sky-700 from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md"
                  href="https://github.com/srinusrinivas07/instagram_mod_app"
                >
                  GitHub
                </a>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-5"
                  href="https://drive.google.com/file/d/1kSh1IDlrPdH6uplemYumn2oMgGx40QLf/view?usp=drive_link"
                >
                  APK
                </a>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-5"
                  href="https://drive.google.com/drive/folders/1t9UuBbwG1n5ls2r_md568dCWGZfimH8n?usp=drive_link"
                >
                  Sample images
                  </a>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1" style={{background: "linear-gradient(to right, #facf6e, #C5FAD5)"}}>
            <h1 className="font-burtons text-xl text-3xl py-1 mb-8 ">FOOD DELIVERY APPLICATION</h1>
              <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md"
                  href="https://github.com/srinusrinivas07/food"
                >
                  GitHub
                </a>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-5"
                  href="https://drive.google.com/file/d/1aH-tpvzpdJ_Eyaz8KloududDXD7mg8ut/view?usp=drive_link"
                >
                  APK
                </a>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-5"
                  href="https://drive.google.com/drive/folders/1dUfqIovOl4ud5QFBrn_K1KzmdTyhMhQo?usp=sharing"
                >
                  Sample images
                </a>
            </div>
            
          </div>
        </section>

        </section>
      </main>
    </div>
    
  );
}
